### ISSUE TITLE
problem with eos-py isntallation

### ISSUE THREAD

**Issue by vishnu41** [patrikhuber/eos#252]
I ran:  pip3 install eos-py
         
error:
static auto call(Args &&...args) -> decltype(visit(std::forward<Args>(args)...)) {
                                                           ^
    python/CMakeFiles/python-bindings.dir/build.make:62: recipe for target 'python/CMakeFiles/python-bindings.dir/generate-python-bindings.cpp.o' failed
    make[2]: *** [python/CMakeFiles/python-bindings.dir/generate-python-bindings.cpp.o] Error 1
    CMakeFiles/Makefile2:140: recipe for target 'python/CMakeFiles/python-bindings.dir/all' failed
    make[1]: *** [python/CMakeFiles/python-bindings.dir/all] Error 2
    Makefile:151: recipe for target 'all' failed
    make: *** [all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-nmd__g4p/eos-py/setup.py", line 79, in <module>
        zip_safe=False,
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.5/distutils/command/install.py", line 583, in run
        self.run_command('build')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.5/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-nmd__g4p/eos-py/setup.py", line 33, in run
        self.build_extension(ext)
      File "/tmp/pip-build-nmd__g4p/eos-py/setup.py", line 60, in build_extension
        subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
      File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j2']' returned non-zero exit status 2
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-nmd__g4p/eos-py/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-kjfzy61n-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-nmd__g4p/eos-py/

**Comment by vishnu41** [comment]
Sorry. I didn't have gcc-7. Problem solved.

**Comment by patrikhuber** [comment]
Cool, that's what I thought, glad you figured it out :-)
